### ISSUE TITLE
orange.rb.rl and violet.ino are not orange and violet respectively. They're white and are listed as "other".

### ISSUE THREAD

**Issue by davenpos** [ozh/rainbow#8]
See [here](https://github.com/ozh/github-colors) for a list of GitHub language colors. I know this repo hasn't been updated in over 10 years, but if you still want it to be a rainbow, it should be updated.

**Comment by ozh** [comment]
Yeah, I'm aware. The colors are constantly changing. It was fun to create the repo with only the minimal commits and commit messages. Also, at that time, the colors where more visible on the top of the page, now they are barely noticeable
